"""
short_service.py — generates a vertical short video using:
  1. A 9:16 image generated by Replicate Flux (same API as thumbnail, different aspect ratio)
  2. Music already produced by music_service
  3. ffmpeg to compose the final video

No Pexels clips are used.
"""

import logging
import os
import random
import subprocess
from pathlib import Path

import replicate
from PIL import Image

from config import Config

logger = logging.getLogger(__name__)

HOOKS = [
    "POV: you enter deep focus mode",
    "POV: coding with no distractions",
    "When the build finally starts flowing",
    "This is what real focus feels like",
    "How developers lock into focus mode",
    "Build mode activated",
    "When the coding vibe is perfect",
    "POV: one more feature before sleep",
    "When the music hits and code just flows",
    "Deep work mode: activated",
]

CONDITION_LINES = [
    "Rainy coding session.",
    "Sunny build mode.",
    "Mountain focus energy.",
    "Beachside deep work.",
    "Late night programming flow.",
    "Calm office focus.",
    "Creative coding session.",
    "No distractions, just code.",
]


def _run(cmd: list) -> None:
    cmd_str = [str(x) for x in cmd]
    logger.info("ffmpeg: %s", " ".join(cmd_str))
    try:
        result = subprocess.run(cmd_str, check=True, capture_output=True, text=True)
        if result.stderr:
            logger.debug("ffmpeg stderr: %s", result.stderr[-2000:])
    except subprocess.CalledProcessError as exc:
        logger.error("ffmpeg failed | returncode=%d | stderr=%s",
                     exc.returncode, exc.stderr[-2000:])
        raise RuntimeError(f"ffmpeg command failed (exit {exc.returncode}).") from exc


def _probe_duration(path) -> float:
    result = subprocess.run(
        ["ffprobe", "-v", "error",
         "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1",
         str(path)],
        capture_output=True, text=True, check=True,
    )
    duration = float(result.stdout.strip())
    logger.debug("Probed duration | path=%s | duration=%.1fs", path, duration)
    return duration


def _generate_short_image(idea: dict, output_dir: Path) -> Path:
    """
    Generate a vertical 9:16 image with Replicate Flux for use in the short video.
    Saves both the original WebP and a converted JPEG.
    Returns the JPEG path.
    """
    token = os.getenv("REPLICATE_API_TOKEN")
    if not token:
        raise RuntimeError(
            "REPLICATE_API_TOKEN not set in environment or keys.env. "
            "Add it to keys.env: REPLICATE_API_TOKEN=r8_..."
        )
    os.environ["REPLICATE_API_TOKEN"] = token

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    webp_path = output_dir / "short_image.webp"
    jpeg_path = output_dir / "short_image.jpg"

    # Vertical-optimised prompt — keeps developer/code in frame for portrait format
    visual_base = idea.get("visual_prompt", "")
    prompt = (
        f"A software developer coding on a laptop, code clearly visible on screen, "
        f"vertical portrait composition, close-up framing, {visual_base}, "
        f"cinematic lighting, immersive atmosphere, "
        f"high quality digital illustration, no text, no watermark"
    )

    logger.info("Generating short image (9:16) with Replicate Flux")
    logger.debug("Short image prompt: %s", prompt)

    try:
        output = replicate.run(
            "black-forest-labs/flux-dev",
            input={
                "prompt": prompt,
                "go_fast": True,
                "guidance": 3.5,
                "megapixels": "1",
                "num_outputs": 1,
                "aspect_ratio": "9:16",
                "output_format": "webp",
                "output_quality": 90,
                "prompt_strength": 0.8,
                "num_inference_steps": 28,
            },
        )
    except Exception as exc:
        logger.error("Replicate short image API call failed: %s", exc)
        raise

    if not output or len(output) == 0:
        raise RuntimeError("Replicate returned empty output for short image.")

    with open(webp_path, "wb") as f:
        f.write(output[0].read())

    webp_kb = webp_path.stat().st_size / 1024
    logger.info("Short WebP saved | path=%s | size_kb=%.1f", webp_path, webp_kb)

    if webp_kb < 1:
        raise RuntimeError(
            f"Short image WebP is suspiciously small ({webp_kb:.1f} KB). "
            "Replicate may have returned an empty image."
        )

    # Convert WebP → JPEG (YouTube does not accept WebP thumbnails)
    img = Image.open(webp_path).convert("RGB")
    img.save(jpeg_path, "JPEG", quality=92)
    logger.info("Short JPEG saved | path=%s | size_kb=%.1f",
                jpeg_path, jpeg_path.stat().st_size / 1024)

    return jpeg_path


def _short_title(idea: dict) -> str:
    hook = random.choice(HOOKS)
    return f"{hook} #shorts"[:100]


def _short_description(idea: dict) -> str:
    condition = random.choice(CONDITION_LINES)
    return (
        f"Coding vibes for developers in deep focus mode.\n\n"
        f"{condition}\n\n"
        f"Full version on the channel.\n\n"
        f"#coding #programming #focus #deepwork #shorts"
    )


def _short_tags() -> list:
    return ["coding", "programming", "focus", "deep work", "shorts", "developer", "ambient music"]


def generate_short(idea: dict, music_path, output_path: Path, temp_dir: Path) -> tuple:
    """
    Generate a short vertical video (9:16):
    - Image: Replicate Flux (9:16 aspect ratio, no Pexels)
    - Audio: slice of the already-generated music
    - Video: composed with ffmpeg

    If temp_dir/short_image.jpg already exists (e.g. from a previous failed run),
    it is reused to avoid paying for another Replicate generation.

    Returns: (str(output_path), meta dict)
    """
    temp_dir = Path(temp_dir)
    temp_dir.mkdir(parents=True, exist_ok=True)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Reuse short image if it already exists (resume safety)
    short_image_path = temp_dir / "short_image.jpg"
    if short_image_path.exists():
        logger.info("Short image already exists, reusing | path=%s | size_kb=%.1f",
                    short_image_path, short_image_path.stat().st_size / 1024)
    else:
        logger.info("Generating short image via Replicate")
        short_image_path = _generate_short_image(idea, temp_dir)

    # Calculate audio segment start
    audio_duration = _probe_duration(music_path)
    configured_offset = Config.short_start_offset_seconds
    if audio_duration <= Config.short_duration_seconds:
        audio_start = 0
    elif configured_offset + Config.short_duration_seconds < audio_duration:
        audio_start = configured_offset
    else:
        audio_start = max(0, int(audio_duration - Config.short_duration_seconds - 1))

    logger.info(
        "Audio segment | full_duration=%.1fs | audio_start=%ds | short_duration=%ds",
        audio_duration, audio_start, Config.short_duration_seconds,
    )
    logger.info("Composing short video with ffmpeg | output=%s", output_path)

    _run([
        "ffmpeg", "-y",
        "-loop", "1",
        "-framerate", "2",
        "-i", str(short_image_path),
        "-ss", str(audio_start),
        "-t", str(Config.short_duration_seconds),
        "-i", str(music_path),
        "-vf", "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,fps=30",
        "-map", "0:v:0",
        "-map", "1:a:0",
        "-c:v", "libx264", "-preset", "veryfast", "-tune", "stillimage",
        "-c:a", "aac", "-b:a", "192k",
        "-pix_fmt", "yuv420p", "-movflags", "+faststart",
        "-shortest",
        str(output_path),
    ])

    size_mb = output_path.stat().st_size / (1024 * 1024)
    logger.info("Short video created | path=%s | size_mb=%.1f", output_path, size_mb)

    meta = {
        "title": _short_title(idea),
        "description": _short_description(idea),
        "tags": _short_tags(),
        "audio_start_seconds": audio_start,
        "short_image_path": str(short_image_path),
    }
    return str(output_path), meta

