"""
short_service.py — generates a vertical short video using:
  1. A 9:16 image generated by Replicate Flux
  2. Music already produced by music_service
  3. ffmpeg to compose the final video
"""

import logging
import os
import subprocess
from pathlib import Path

import replicate
from PIL import Image

from config import Config

logger = logging.getLogger(__name__)


def _run(cmd: list) -> None:
    cmd_str = [str(x) for x in cmd]
    logger.info("ffmpeg: %s", " ".join(cmd_str))
    result = subprocess.run(cmd_str, check=True, capture_output=True, text=True)
    if result.stderr:
        logger.debug("ffmpeg stderr: %s", result.stderr[-2000:])


def _probe_duration(path) -> float:
    result = subprocess.run(
        [
            "ffprobe", "-v", "error",
            "-show_entries", "format=duration",
            "-of", "default=noprint_wrappers=1:nokey=1",
            str(path),
        ],
        capture_output=True, text=True, check=True,
    )
    return float(result.stdout.strip())


def _generate_short_image(idea: dict, output_dir: Path) -> Path:
    token = os.getenv("REPLICATE_API_TOKEN")
    if not token:
        raise RuntimeError("REPLICATE_API_TOKEN not set in environment or keys.env.")
    os.environ["REPLICATE_API_TOKEN"] = token

    output_dir.mkdir(parents=True, exist_ok=True)
    webp_path = output_dir / "short_image.webp"
    jpeg_path = output_dir / "short_image.jpg"

    prompt = (
        f"A software developer coding on a laptop, code clearly visible on screen, vertical portrait composition, "
        f"close-up framing, in {idea.get('place')}, during {idea.get('time_of_day')}, with {idea.get('weather')}, "
        f"cinematic lighting, immersive atmosphere, high quality digital illustration, no text, no watermark"
    )

    output = replicate.run(
        "black-forest-labs/flux-dev",
        input={
            "prompt": prompt,
            "go_fast": True,
            "guidance": 3.5,
            "megapixels": "1",
            "num_outputs": 1,
            "aspect_ratio": "9:16",
            "output_format": "webp",
            "output_quality": 90,
            "prompt_strength": 0.8,
            "num_inference_steps": 28,
        },
    )

    if not output:
        raise RuntimeError("Replicate returned empty output for short image.")

    with open(webp_path, "wb") as f:
        f.write(output[0].read())

    img = Image.open(webp_path).convert("RGB")
    img.save(jpeg_path, "JPEG", quality=92)
    return jpeg_path


def _short_title(idea: dict) -> str:
    return f"{idea.get('time_of_day', 'Focus').title()} coding in {idea.get('place')} #shorts"[:100]


def _short_description(idea: dict) -> str:
    return (
        f"{idea.get('time_of_day', '').title()} coding in {idea.get('place')} with {idea.get('weather')}.\n\n"
        f"Same vibe as the full session on the channel.\n\n"
        f"#coding #programming #focus #deepwork #shorts"
    )


def _short_tags(idea: dict) -> list:
    city = str(idea.get('place', '')).split(',')[0].lower()
    return ["coding", "programming", "focus", "deep work", "shorts", city, "developer"]


def generate_short(idea: dict, music_path, output_path: Path, temp_dir: Path) -> tuple:
    temp_dir = Path(temp_dir)
    temp_dir.mkdir(parents=True, exist_ok=True)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    short_image_path = temp_dir / "short_image.jpg"
    if not short_image_path.exists():
        short_image_path = _generate_short_image(idea, temp_dir)

    audio_duration = _probe_duration(music_path)
    configured_offset = Config.short_start_offset_seconds
    if audio_duration <= Config.short_duration_seconds:
        audio_start = 0
    elif configured_offset + Config.short_duration_seconds < audio_duration:
        audio_start = configured_offset
    else:
        audio_start = max(0, int(audio_duration - Config.short_duration_seconds - 1))

    _run([
        "ffmpeg", "-y",
        "-loop", "1",
        "-framerate", "2",
        "-i", str(short_image_path),
        "-ss", str(audio_start),
        "-t", str(Config.short_duration_seconds),
        "-i", str(music_path),
        "-vf", "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,fps=30",
        "-map", "0:v:0",
        "-map", "1:a:0",
        "-c:v", "libx264", "-preset", "veryfast", "-tune", "stillimage",
        "-c:a", "aac", "-b:a", "192k",
        "-pix_fmt", "yuv420p", "-movflags", "+faststart",
        "-shortest",
        str(output_path),
    ])

    meta = {
        "title": _short_title(idea),
        "description": _short_description(idea),
        "tags": _short_tags(idea),
        "audio_start_seconds": audio_start,
        "short_image_path": str(short_image_path),
    }
    return str(output_path), meta
